name: EditorConfig

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run editorconfig
    env:
      EC_VERSION: v3.0.3 # Used for `editorconfig-checker`. Issue: https://github.com/editorconfig-checker/editorconfig-checker/issues/409
